### ISSUE TITLE
TODO list

### ISSUE THREAD

**Issue by cweagans** [cweagans/php-webdam-client#1]
- [ ] API complete
  - [ ] GET /folders
  - [ ] GET /folders/:folderid
  - [ ] GET /folders/list?ids=123,456
  - [ ] POST /folders
  - [ ] PUT /folders/:folderid
  - [ ] DELETE /folders/:folderid
  - [ ] GET /assets/:assetid
  - [ ] GET /assets/list?ids=123,456
  - [ ] DELETE /assets/:assetid
  - [ ] Asset upload (optimized)
  - [ ] GET /assets/:id/download
  - [ ] GET /assets/:assetid/versions
  - [ ] GET /assets/:assetid/versions/:version
  - [ ] DELETE /assets/:assetid/versions/:version
  - [ ] POST /assets/:assetid/versions/:version
  - [ ] GET /assets/:assetid/versions/:version/download
  - [ ] GET /assets/:assetid/related
  - [ ] POST /assets/:assetid/senddownload
  - [ ] GET /assets/:assetid/metadatas/xmp
  - [ ] PUT /assets/:assetid/metadatas/xmp
  - [ ] GET /assets/:id/metadatas/exif
  - [ ] GET /metadatatemplates
  - [ ] GET /metadatatemplates/:templateid
  - [ ] POST /metadatatemplates
  - [ ] PUT /metadatatemplates/:templateid
  - [ ] DELETE /metadatatemplates/:templateid
  - [ ] POST /metadatatemplates/:templateid/apply
  - [ ] GET /metadataschemas/xmp
  - [ ] POST /metadataschemas/xmp
  - [ ] GET /lightboxes
  - [ ] GET /lightboxes/:lightboxid
  - [ ] POST /lightboxes
  - [ ] PUT /lightboxes/:lightboxid
  - [ ] DELETE /lightboxes/:lightboxid
  - [ ] GET /lightboxes/:lightboxid/assets
  - [ ] POST /lightboxes/:lightboxid/assets
  - [ ] DELETE /lightboxes/:lightboxid/assets/:assetid
  - [ ] DELETE /lightboxes/:lightboxid/empty
  - [ ] GET /lightboxes/:lightboxid/collaborators
  - [ ] POST /lightboxes/:lightboxid/collaborators
  - [ ] DELETE /lightboxes/:lightboxid/collaborators/:collaboratorid
  - [ ] POST /lightboxes/:lightboxid/senddownload
  - [ ] GET /lightboxes/:lightboxid/comments
  - [ ] GET /lightboxes/:lightboxid/comments/:commentid
  - [ ] POST /lightboxes/:lightboxid/comments
  - [ ] DELETE /lightboxes/:lightboxid/comments/:commentid
  - [ ] GET /lightboxes/:lightboxid/assets/:assetid/comments
  - [ ] GET /lightboxes/:lightboxid/assets/:assetid/comments/:commentid
  - [ ] POST /lightboxes/:lightboxid/assets/:assetid/comments
  - [ ] DELETE /lightboxes/:lightboxid/assets/:assetid/comments/:commentid
  - [ ] GET /search
  - [ ] GET /groups
  - [ ] GET /groups/:groupid
  - [ ] POST /groups
  - [ ] PUT /groups/:groupid
  - [ ] DELETE /groups/:groupid
  - [ ] GET /groups/:groupid/users
  - [ ] POST /groups/:groupid/users/:userid
  - [ ] POST /groups/:groupid/users/:userid
  - [ ] GET /users
  - [ ] GET /users/me
  - [ ] GET /users/:userid
  - [ ] GET /users/:userid/groups
  - [ ] POST /users
  - [ ] PUT /users/:userid
  - [ ] PUT /users/me
  - [ ] DELETE /users/:userid
  - [x] GET /subscription
  - [ ] GET /notifications
- [ ] Nice convenience methods on Entity objects (i.e. $folder->getChildFolder(1)->getFirstAsset()->getUser()->getName() or something)
- [ ]  Tests for all the things
- [ ] Reconcile test JSON against API JSON and make sure properties are accurately represented and tested
- [x] ~Client side caching~ Use https://github.com/Kevinrob/guzzle-cache-middleware instead
- [ ] Stream wrapper?
